name: AutoMessages
version: '${version}'
main: ru.shandydev.automessages.AutoMessages
api-version: '1.20'
load: STARTUP
commands:
  am:
    description: "Automessages command"
    usage: "/am"
    aliases: ["automsg", "automessages"]
