name: Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew shadowJar

      - name: Get plugin version
        id: get_version
        run: |
          echo "version_name=$(./gradlew -q printVersionName)" >> $GITHUB_ENV
    outputs:
      version_name: ${{ steps.get_version.outputs.version_name }}
      jar_file: build/libs/AutoMessages-${{ steps.get_version.outputs.version_name }}.jar

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v2.0.5
        with:
          tag_name: ${{needs.build.outputs.version_name}}
          release_name: Release ${{needs.build.outputs.version_name}}
          draft: false
          files: ${{needs.build.outputs.jar_file}}
